#!/bin/bash

__BUS_OPTIONS_TABLE=()

add-option() {
    local LONGNAME="NULL"
    local SHORTNAME="NULL"
    local ACTION=store
    local HELP="NULL"

    while [ $# -gt 0 ]; do
        case "$1" in
            -l|--long-name)
                LONGNAME=$2
                shift 2
                ;;
            -s|--short-name)
                SHORTNAME=$2
                shift 2
                ;;
            -a|--action)
                case $2 in store|store_true)
                    ACTION=$2
                    shift 2
                    ;;
                *)
                    echo "error! $FUNCNAME: unsupported action, $2"
                    exit -1
                    ;;
                esac
                ;;
            -h|--help)
                HELP=$2
                shift 2
                ;;
            *)
                echo "error! $FUNCNAME: unrecognized option, $1"
                exit -1
                ;;
        esac
    done

    if [ "$LONGNAME" == "NULL" ] && [ "$SHORTNAME" == "NULL" ]; then
        echo "error! $FUNCNAME: option must have either shortname or longname, or both"
        exit -1
    fi

    __BUS_OPTIONS_TABLE+=("$LONGNAME $SHORTNAME $ACTION $HELP")
}

parse-options() {
    while [ $# -gt 0 ]; do
        local OPTION_FOUND=false

        if [[ $1 == -* ]]; then
            if [[ $1 == "--__list_options" ]]; then
                __BUS_LIST_OPTIONS=true
                shift
                continue
            fi

            for OPTION_STRING in "${__BUS_OPTIONS_TABLE[@]}"; do
                local OPTION_ARRAY=($OPTION_STRING)
                local LONGNAME=${OPTION_ARRAY[0]}
                local SHORTNAME=${OPTION_ARRAY[1]}
                local ACTION=${OPTION_ARRAY[2]}
                local VARNAME=__BUS_OPTION_${LONGNAME:-$SHORTNAME}

                if [ "$1" == "--$LONGNAME" ] || [ "$1" == "-$SHORTNAME" ]; then
                    case $ACTION in
                        store)
                            local ARG="$2"
                            if [[ $ARG == -* ]] || [[ -z $ARG ]]; then
                                echo "error! option $1 takes an argument"
                                exit 0
                            fi
                            read "$VARNAME" <<< "$ARG"
                            shift
                            ;;
                        store_true)
                            read "$VARNAME" <<< "true"
                            ;;
                    esac
                    OPTION_FOUND=true
                    break
                fi
            done

            if [[ $OPTION_FOUND == true ]]; then
                shift
                continue
            fi
            echo "unknown option $1"
            exit -1
        else
            __BUS_ARGS=$@
            return
        fi
    done
}

get-option() {
    local VARNAME=__BUS_OPTION_$1
    echo "${!VARNAME}"
}

list-options() {
    if [[ $__BUS_LIST_OPTIONS == true ]]; then
        for OPTION_STRING in "${__BUS_OPTIONS_TABLE[@]}"; do
            local OPTION_ARRAY=($OPTION_STRING)
            local LONGNAME=${OPTION_ARRAY[0]}
            [[ ! $LONGNAME == NULL ]] && OPTIONS+="--$LONGNAME "
        done
        echo "$OPTIONS"
        exit 0
    fi
}
